on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd python/python && make clean check all && cd ../..
          cd python/ && make clean check all && cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: anonymize-excel-linux
          path: python/tmp/dist/anonymize-excel
  make-windows:
    runs-on: windows-2022
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd python/ && python3 -m pip install --upgrade pip && python3 -m pip install .[dev] && python3 main.py && cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: anonymize-excel-windows
          path: python/tmp/dist/anonymize-excel.exe
  make-macos:
    runs-on: macos-14
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd python/ && python3 -m pip install --upgrade pip && python3 -m pip install .[dev] && python3 main.py && cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: anonymize-excel-macos
          path: python/tmp/dist/anonymize-excel
  pip:
    needs: [make,make-windows,make-macos]
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022,macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Check pip installation
        run: |
          pip install https://api.github.com/repos/valab-certh/anonymize-excel/tarball/main#subdirectory=python/python
          anonymize_excel "python/prm/samples/valab"
  release:
    needs: [make,make-windows,make-macos]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ github.workspace }}/anonymize-excel-windows/anonymize-excel.exe
            ${{ github.workspace }}/anonymize-excel-linux/anonymize-excel
            ${{ github.workspace }}/anonymize-excel-macos/anonymize-excel
          draft: true
          tag: "dist"
          commit: main